import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Suspense } from "react";
import Loading from "./loading";

import HeaderWrapper from "./HeaderWrapper";
import { Footer } from "./footer";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/src/i18n/routing";
import { notFound } from "next/navigation";

import Template from "./template";  // шаблон анимации
import ReduxProvider from "./reduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TajWorks",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              document.addEventListener("DOMContentLoaded", function () {
                document.documentElement.classList.remove("no-transitions");
              });
            `,
          }}
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Suspense fallback={<Loading />}>
          <NextIntlClientProvider>
            <header className="fixed top-0 left-0 w-full z-50 border-b bg-white/5 backdrop-blur-lg dark:bg-background/30">
              <HeaderWrapper />
            </header>

            {/* Анимационная обёртка */}
            <Template>
              <ReduxProvider>
                <main className="pt-20">{children}</main>
              </ReduxProvider>
            </Template>

            <footer>
              <Footer />
            </footer>
          </NextIntlClientProvider>
        </Suspense>
      </body>
    </html>
  );
}
